'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AufgabeEntity
    Public Property aufIdPk As Integer
    Public Property aufTitel As String
    Public Property aufBeschreibung As String
    Public Property aufFaellig As Nullable(Of Date)
    Public Property aufErledigt As Nullable(Of Boolean)

End Class
